spring:
  datasource:
    password: mysql
    url: jdbc:mysql://localhost:3306/ashok_sir
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
